// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package profile

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AcceptRoleSessionName, b.ko.Spec.AcceptRoleSessionName) {
		delta.Add("Spec.AcceptRoleSessionName", a.ko.Spec.AcceptRoleSessionName, b.ko.Spec.AcceptRoleSessionName)
	} else if a.ko.Spec.AcceptRoleSessionName != nil && b.ko.Spec.AcceptRoleSessionName != nil {
		if *a.ko.Spec.AcceptRoleSessionName != *b.ko.Spec.AcceptRoleSessionName {
			delta.Add("Spec.AcceptRoleSessionName", a.ko.Spec.AcceptRoleSessionName, b.ko.Spec.AcceptRoleSessionName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DurationSeconds, b.ko.Spec.DurationSeconds) {
		delta.Add("Spec.DurationSeconds", a.ko.Spec.DurationSeconds, b.ko.Spec.DurationSeconds)
	} else if a.ko.Spec.DurationSeconds != nil && b.ko.Spec.DurationSeconds != nil {
		if *a.ko.Spec.DurationSeconds != *b.ko.Spec.DurationSeconds {
			delta.Add("Spec.DurationSeconds", a.ko.Spec.DurationSeconds, b.ko.Spec.DurationSeconds)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if len(a.ko.Spec.ManagedPolicyARNs) != len(b.ko.Spec.ManagedPolicyARNs) {
		delta.Add("Spec.ManagedPolicyARNs", a.ko.Spec.ManagedPolicyARNs, b.ko.Spec.ManagedPolicyARNs)
	} else if len(a.ko.Spec.ManagedPolicyARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedPolicyARNs, b.ko.Spec.ManagedPolicyARNs) {
			delta.Add("Spec.ManagedPolicyARNs", a.ko.Spec.ManagedPolicyARNs, b.ko.Spec.ManagedPolicyARNs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RequireInstanceProperties, b.ko.Spec.RequireInstanceProperties) {
		delta.Add("Spec.RequireInstanceProperties", a.ko.Spec.RequireInstanceProperties, b.ko.Spec.RequireInstanceProperties)
	} else if a.ko.Spec.RequireInstanceProperties != nil && b.ko.Spec.RequireInstanceProperties != nil {
		if *a.ko.Spec.RequireInstanceProperties != *b.ko.Spec.RequireInstanceProperties {
			delta.Add("Spec.RequireInstanceProperties", a.ko.Spec.RequireInstanceProperties, b.ko.Spec.RequireInstanceProperties)
		}
	}
	if len(a.ko.Spec.RoleARNs) != len(b.ko.Spec.RoleARNs) {
		delta.Add("Spec.RoleARNs", a.ko.Spec.RoleARNs, b.ko.Spec.RoleARNs)
	} else if len(a.ko.Spec.RoleARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.RoleARNs, b.ko.Spec.RoleARNs) {
			delta.Add("Spec.RoleARNs", a.ko.Spec.RoleARNs, b.ko.Spec.RoleARNs)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RoleRefs, b.ko.Spec.RoleRefs) {
		delta.Add("Spec.RoleRefs", a.ko.Spec.RoleRefs, b.ko.Spec.RoleRefs)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SessionPolicy, b.ko.Spec.SessionPolicy) {
		delta.Add("Spec.SessionPolicy", a.ko.Spec.SessionPolicy, b.ko.Spec.SessionPolicy)
	} else if a.ko.Spec.SessionPolicy != nil && b.ko.Spec.SessionPolicy != nil {
		if *a.ko.Spec.SessionPolicy != *b.ko.Spec.SessionPolicy {
			delta.Add("Spec.SessionPolicy", a.ko.Spec.SessionPolicy, b.ko.Spec.SessionPolicy)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
