// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package profile

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/rolesanywhere"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/rolesanywhere/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/rolesanywhere-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Profile{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetProfileOutput
	resp, err = rm.sdkapi.GetProfile(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetProfile", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Profile.AcceptRoleSessionName != nil {
		ko.Spec.AcceptRoleSessionName = resp.Profile.AcceptRoleSessionName
	} else {
		ko.Spec.AcceptRoleSessionName = nil
	}
	if resp.Profile.AttributeMappings != nil {
		f1 := []*svcapitypes.AttributeMapping{}
		for _, f1iter := range resp.Profile.AttributeMappings {
			f1elem := &svcapitypes.AttributeMapping{}
			if f1iter.CertificateField != "" {
				f1elem.CertificateField = aws.String(string(f1iter.CertificateField))
			}
			if f1iter.MappingRules != nil {
				f1elemf1 := []*svcapitypes.MappingRule{}
				for _, f1elemf1iter := range f1iter.MappingRules {
					f1elemf1elem := &svcapitypes.MappingRule{}
					if f1elemf1iter.Specifier != nil {
						f1elemf1elem.Specifier = f1elemf1iter.Specifier
					}
					f1elemf1 = append(f1elemf1, f1elemf1elem)
				}
				f1elem.MappingRules = f1elemf1
			}
			f1 = append(f1, f1elem)
		}
		ko.Status.AttributeMappings = f1
	} else {
		ko.Status.AttributeMappings = nil
	}
	if resp.Profile.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Profile.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Profile.CreatedBy != nil {
		ko.Status.CreatedBy = resp.Profile.CreatedBy
	} else {
		ko.Status.CreatedBy = nil
	}
	if resp.Profile.DurationSeconds != nil {
		durationSecondsCopy := int64(*resp.Profile.DurationSeconds)
		ko.Spec.DurationSeconds = &durationSecondsCopy
	} else {
		ko.Spec.DurationSeconds = nil
	}
	if resp.Profile.Enabled != nil {
		ko.Spec.Enabled = resp.Profile.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.Profile.ManagedPolicyArns != nil {
		ko.Spec.ManagedPolicyARNs = aws.StringSlice(resp.Profile.ManagedPolicyArns)
	} else {
		ko.Spec.ManagedPolicyARNs = nil
	}
	if resp.Profile.Name != nil {
		ko.Spec.Name = resp.Profile.Name
	} else {
		ko.Spec.Name = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Profile.ProfileArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Profile.ProfileArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Profile.ProfileId != nil {
		ko.Status.ProfileID = resp.Profile.ProfileId
	} else {
		ko.Status.ProfileID = nil
	}
	if resp.Profile.RequireInstanceProperties != nil {
		ko.Spec.RequireInstanceProperties = resp.Profile.RequireInstanceProperties
	} else {
		ko.Spec.RequireInstanceProperties = nil
	}
	if resp.Profile.RoleArns != nil {
		ko.Spec.RoleARNs = aws.StringSlice(resp.Profile.RoleArns)
	} else {
		ko.Spec.RoleARNs = nil
	}
	if resp.Profile.SessionPolicy != nil {
		ko.Spec.SessionPolicy = resp.Profile.SessionPolicy
	} else {
		ko.Spec.SessionPolicy = nil
	}
	if resp.Profile.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Profile.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ProfileID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetProfileInput, error) {
	res := &svcsdk.GetProfileInput{}

	if r.ko.Status.ProfileID != nil {
		res.ProfileId = r.ko.Status.ProfileID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateProfileOutput
	_ = resp
	resp, err = rm.sdkapi.CreateProfile(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateProfile", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Profile.AcceptRoleSessionName != nil {
		ko.Spec.AcceptRoleSessionName = resp.Profile.AcceptRoleSessionName
	} else {
		ko.Spec.AcceptRoleSessionName = nil
	}
	if resp.Profile.AttributeMappings != nil {
		f1 := []*svcapitypes.AttributeMapping{}
		for _, f1iter := range resp.Profile.AttributeMappings {
			f1elem := &svcapitypes.AttributeMapping{}
			if f1iter.CertificateField != "" {
				f1elem.CertificateField = aws.String(string(f1iter.CertificateField))
			}
			if f1iter.MappingRules != nil {
				f1elemf1 := []*svcapitypes.MappingRule{}
				for _, f1elemf1iter := range f1iter.MappingRules {
					f1elemf1elem := &svcapitypes.MappingRule{}
					if f1elemf1iter.Specifier != nil {
						f1elemf1elem.Specifier = f1elemf1iter.Specifier
					}
					f1elemf1 = append(f1elemf1, f1elemf1elem)
				}
				f1elem.MappingRules = f1elemf1
			}
			f1 = append(f1, f1elem)
		}
		ko.Status.AttributeMappings = f1
	} else {
		ko.Status.AttributeMappings = nil
	}
	if resp.Profile.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Profile.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Profile.CreatedBy != nil {
		ko.Status.CreatedBy = resp.Profile.CreatedBy
	} else {
		ko.Status.CreatedBy = nil
	}
	if resp.Profile.DurationSeconds != nil {
		durationSecondsCopy := int64(*resp.Profile.DurationSeconds)
		ko.Spec.DurationSeconds = &durationSecondsCopy
	} else {
		ko.Spec.DurationSeconds = nil
	}
	if resp.Profile.Enabled != nil {
		ko.Spec.Enabled = resp.Profile.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.Profile.ManagedPolicyArns != nil {
		ko.Spec.ManagedPolicyARNs = aws.StringSlice(resp.Profile.ManagedPolicyArns)
	} else {
		ko.Spec.ManagedPolicyARNs = nil
	}
	if resp.Profile.Name != nil {
		ko.Spec.Name = resp.Profile.Name
	} else {
		ko.Spec.Name = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Profile.ProfileArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Profile.ProfileArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Profile.ProfileId != nil {
		ko.Status.ProfileID = resp.Profile.ProfileId
	} else {
		ko.Status.ProfileID = nil
	}
	if resp.Profile.RequireInstanceProperties != nil {
		ko.Spec.RequireInstanceProperties = resp.Profile.RequireInstanceProperties
	} else {
		ko.Spec.RequireInstanceProperties = nil
	}
	if resp.Profile.RoleArns != nil {
		ko.Spec.RoleARNs = aws.StringSlice(resp.Profile.RoleArns)
	} else {
		ko.Spec.RoleARNs = nil
	}
	if resp.Profile.SessionPolicy != nil {
		ko.Spec.SessionPolicy = resp.Profile.SessionPolicy
	} else {
		ko.Spec.SessionPolicy = nil
	}
	if resp.Profile.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Profile.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateProfileInput, error) {
	res := &svcsdk.CreateProfileInput{}

	if r.ko.Spec.AcceptRoleSessionName != nil {
		res.AcceptRoleSessionName = r.ko.Spec.AcceptRoleSessionName
	}
	if r.ko.Spec.DurationSeconds != nil {
		durationSecondsCopy0 := *r.ko.Spec.DurationSeconds
		if durationSecondsCopy0 > math.MaxInt32 || durationSecondsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field durationSeconds is of type int32")
		}
		durationSecondsCopy := int32(durationSecondsCopy0)
		res.DurationSeconds = &durationSecondsCopy
	}
	if r.ko.Spec.Enabled != nil {
		res.Enabled = r.ko.Spec.Enabled
	}
	if r.ko.Spec.ManagedPolicyARNs != nil {
		res.ManagedPolicyArns = aws.ToStringSlice(r.ko.Spec.ManagedPolicyARNs)
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.RequireInstanceProperties != nil {
		res.RequireInstanceProperties = r.ko.Spec.RequireInstanceProperties
	}
	if r.ko.Spec.RoleARNs != nil {
		res.RoleArns = aws.ToStringSlice(r.ko.Spec.RoleARNs)
	}
	if r.ko.Spec.SessionPolicy != nil {
		res.SessionPolicy = r.ko.Spec.SessionPolicy
	}
	if r.ko.Spec.Tags != nil {
		f8 := []svcsdktypes.Tag{}
		for _, f8iter := range r.ko.Spec.Tags {
			f8elem := &svcsdktypes.Tag{}
			if f8iter.Key != nil {
				f8elem.Key = f8iter.Key
			}
			if f8iter.Value != nil {
				f8elem.Value = f8iter.Value
			}
			f8 = append(f8, *f8elem)
		}
		res.Tags = f8
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// Sync enabled/disabled state after update (Enable/Disable are separate API calls)
	if desired.ko.Spec.Enabled != nil {
		desiredEnabled := *desired.ko.Spec.Enabled
		currentEnabled := true
		if latest.ko.Spec.Enabled != nil {
			currentEnabled = *latest.ko.Spec.Enabled
		}
		if desiredEnabled != currentEnabled {
			if desiredEnabled {
				_, err = rm.sdkapi.EnableProfile(ctx, &svcsdk.EnableProfileInput{
					ProfileId: latest.ko.Status.ProfileID,
				})
			} else {
				_, err = rm.sdkapi.DisableProfile(ctx, &svcsdk.DisableProfileInput{
					ProfileId: latest.ko.Status.ProfileID,
				})
			}
			if err != nil {
				return nil, err
			}
		}
	}

	var resp *svcsdk.UpdateProfileOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateProfile(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateProfile", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Profile.AcceptRoleSessionName != nil {
		ko.Spec.AcceptRoleSessionName = resp.Profile.AcceptRoleSessionName
	} else {
		ko.Spec.AcceptRoleSessionName = nil
	}
	if resp.Profile.AttributeMappings != nil {
		f1 := []*svcapitypes.AttributeMapping{}
		for _, f1iter := range resp.Profile.AttributeMappings {
			f1elem := &svcapitypes.AttributeMapping{}
			if f1iter.CertificateField != "" {
				f1elem.CertificateField = aws.String(string(f1iter.CertificateField))
			}
			if f1iter.MappingRules != nil {
				f1elemf1 := []*svcapitypes.MappingRule{}
				for _, f1elemf1iter := range f1iter.MappingRules {
					f1elemf1elem := &svcapitypes.MappingRule{}
					if f1elemf1iter.Specifier != nil {
						f1elemf1elem.Specifier = f1elemf1iter.Specifier
					}
					f1elemf1 = append(f1elemf1, f1elemf1elem)
				}
				f1elem.MappingRules = f1elemf1
			}
			f1 = append(f1, f1elem)
		}
		ko.Status.AttributeMappings = f1
	} else {
		ko.Status.AttributeMappings = nil
	}
	if resp.Profile.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Profile.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Profile.CreatedBy != nil {
		ko.Status.CreatedBy = resp.Profile.CreatedBy
	} else {
		ko.Status.CreatedBy = nil
	}
	if resp.Profile.DurationSeconds != nil {
		durationSecondsCopy := int64(*resp.Profile.DurationSeconds)
		ko.Spec.DurationSeconds = &durationSecondsCopy
	} else {
		ko.Spec.DurationSeconds = nil
	}
	if resp.Profile.Enabled != nil {
		ko.Spec.Enabled = resp.Profile.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.Profile.ManagedPolicyArns != nil {
		ko.Spec.ManagedPolicyARNs = aws.StringSlice(resp.Profile.ManagedPolicyArns)
	} else {
		ko.Spec.ManagedPolicyARNs = nil
	}
	if resp.Profile.Name != nil {
		ko.Spec.Name = resp.Profile.Name
	} else {
		ko.Spec.Name = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Profile.ProfileArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Profile.ProfileArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Profile.RequireInstanceProperties != nil {
		ko.Spec.RequireInstanceProperties = resp.Profile.RequireInstanceProperties
	} else {
		ko.Spec.RequireInstanceProperties = nil
	}
	if resp.Profile.RoleArns != nil {
		ko.Spec.RoleARNs = aws.StringSlice(resp.Profile.RoleArns)
	} else {
		ko.Spec.RoleARNs = nil
	}
	if resp.Profile.SessionPolicy != nil {
		ko.Spec.SessionPolicy = resp.Profile.SessionPolicy
	} else {
		ko.Spec.SessionPolicy = nil
	}
	if resp.Profile.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Profile.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateProfileInput, error) {
	res := &svcsdk.UpdateProfileInput{}

	if r.ko.Spec.AcceptRoleSessionName != nil {
		res.AcceptRoleSessionName = r.ko.Spec.AcceptRoleSessionName
	}
	if r.ko.Spec.DurationSeconds != nil {
		durationSecondsCopy0 := *r.ko.Spec.DurationSeconds
		if durationSecondsCopy0 > math.MaxInt32 || durationSecondsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field durationSeconds is of type int32")
		}
		durationSecondsCopy := int32(durationSecondsCopy0)
		res.DurationSeconds = &durationSecondsCopy
	}
	if r.ko.Spec.ManagedPolicyARNs != nil {
		res.ManagedPolicyArns = aws.ToStringSlice(r.ko.Spec.ManagedPolicyARNs)
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.RoleARNs != nil {
		res.RoleArns = aws.ToStringSlice(r.ko.Spec.RoleARNs)
	}
	if r.ko.Spec.SessionPolicy != nil {
		res.SessionPolicy = r.ko.Spec.SessionPolicy
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	// Disable profile before deletion (API requirement)
	if r.ko.Spec.Enabled == nil || *r.ko.Spec.Enabled {
		_, _ = rm.sdkapi.DisableProfile(ctx, &svcsdk.DisableProfileInput{
			ProfileId: r.ko.Status.ProfileID,
		})
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteProfileOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteProfile(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteProfile", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteProfileInput, error) {
	res := &svcsdk.DeleteProfileInput{}

	if r.ko.Status.ProfileID != nil {
		res.ProfileId = r.ko.Status.ProfileID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Profile,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ResourceNotFoundException",
		"ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
