// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package trust_anchor

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.NotificationSettings) != len(b.ko.Spec.NotificationSettings) {
		delta.Add("Spec.NotificationSettings", a.ko.Spec.NotificationSettings, b.ko.Spec.NotificationSettings)
	} else if len(a.ko.Spec.NotificationSettings) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.NotificationSettings, b.ko.Spec.NotificationSettings) {
			delta.Add("Spec.NotificationSettings", a.ko.Spec.NotificationSettings, b.ko.Spec.NotificationSettings)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Source, b.ko.Spec.Source) {
		delta.Add("Spec.Source", a.ko.Spec.Source, b.ko.Spec.Source)
	} else if a.ko.Spec.Source != nil && b.ko.Spec.Source != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Source.SourceData, b.ko.Spec.Source.SourceData) {
			delta.Add("Spec.Source.SourceData", a.ko.Spec.Source.SourceData, b.ko.Spec.Source.SourceData)
		} else if a.ko.Spec.Source.SourceData != nil && b.ko.Spec.Source.SourceData != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Source.SourceData.ACMPCAARN, b.ko.Spec.Source.SourceData.ACMPCAARN) {
				delta.Add("Spec.Source.SourceData.ACMPCAARN", a.ko.Spec.Source.SourceData.ACMPCAARN, b.ko.Spec.Source.SourceData.ACMPCAARN)
			} else if a.ko.Spec.Source.SourceData.ACMPCAARN != nil && b.ko.Spec.Source.SourceData.ACMPCAARN != nil {
				if *a.ko.Spec.Source.SourceData.ACMPCAARN != *b.ko.Spec.Source.SourceData.ACMPCAARN {
					delta.Add("Spec.Source.SourceData.ACMPCAARN", a.ko.Spec.Source.SourceData.ACMPCAARN, b.ko.Spec.Source.SourceData.ACMPCAARN)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Source.SourceData.X509CertificateData, b.ko.Spec.Source.SourceData.X509CertificateData) {
				delta.Add("Spec.Source.SourceData.X509CertificateData", a.ko.Spec.Source.SourceData.X509CertificateData, b.ko.Spec.Source.SourceData.X509CertificateData)
			} else if a.ko.Spec.Source.SourceData.X509CertificateData != nil && b.ko.Spec.Source.SourceData.X509CertificateData != nil {
				if *a.ko.Spec.Source.SourceData.X509CertificateData != *b.ko.Spec.Source.SourceData.X509CertificateData {
					delta.Add("Spec.Source.SourceData.X509CertificateData", a.ko.Spec.Source.SourceData.X509CertificateData, b.ko.Spec.Source.SourceData.X509CertificateData)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Source.SourceType, b.ko.Spec.Source.SourceType) {
			delta.Add("Spec.Source.SourceType", a.ko.Spec.Source.SourceType, b.ko.Spec.Source.SourceType)
		} else if a.ko.Spec.Source.SourceType != nil && b.ko.Spec.Source.SourceType != nil {
			if *a.ko.Spec.Source.SourceType != *b.ko.Spec.Source.SourceType {
				delta.Add("Spec.Source.SourceType", a.ko.Spec.Source.SourceType, b.ko.Spec.Source.SourceType)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
