// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package trust_anchor

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/rolesanywhere"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/rolesanywhere/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/rolesanywhere-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.TrustAnchor{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetTrustAnchorOutput
	resp, err = rm.sdkapi.GetTrustAnchor(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetTrustAnchor", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.TrustAnchor.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.TrustAnchor.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.TrustAnchor.Enabled != nil {
		ko.Spec.Enabled = resp.TrustAnchor.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.TrustAnchor.Name != nil {
		ko.Spec.Name = resp.TrustAnchor.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.TrustAnchor.NotificationSettings != nil {
		f3 := []*svcapitypes.NotificationSetting{}
		for _, f3iter := range resp.TrustAnchor.NotificationSettings {
			f3elem := &svcapitypes.NotificationSetting{}
			if f3iter.Channel != "" {
				f3elem.Channel = aws.String(string(f3iter.Channel))
			}
			if f3iter.Enabled != nil {
				f3elem.Enabled = f3iter.Enabled
			}
			if f3iter.Event != "" {
				f3elem.Event = aws.String(string(f3iter.Event))
			}
			if f3iter.Threshold != nil {
				thresholdCopy := int64(*f3iter.Threshold)
				f3elem.Threshold = &thresholdCopy
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.NotificationSettings = f3
	} else {
		ko.Spec.NotificationSettings = nil
	}
	if resp.TrustAnchor.Source != nil {
		f4 := &svcapitypes.Source{}
		if resp.TrustAnchor.Source.SourceData != nil {
			f4f0 := &svcapitypes.SourceData{}
			switch resp.TrustAnchor.Source.SourceData.(type) {
			case *svcsdktypes.SourceDataMemberAcmPcaArn:
				f4f0f0 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberAcmPcaArn)
				if f4f0f0 != nil {
					f4f0.ACMPCAARN = &f4f0f0.Value
				}
			case *svcsdktypes.SourceDataMemberX509CertificateData:
				f4f0f1 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberX509CertificateData)
				if f4f0f1 != nil {
					f4f0.X509CertificateData = &f4f0f1.Value
				}
			}
			f4.SourceData = f4f0
		}
		if resp.TrustAnchor.Source.SourceType != "" {
			f4.SourceType = aws.String(string(resp.TrustAnchor.Source.SourceType))
		}
		ko.Spec.Source = f4
	} else {
		ko.Spec.Source = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TrustAnchor.TrustAnchorArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TrustAnchor.TrustAnchorArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.TrustAnchor.TrustAnchorId != nil {
		ko.Status.TrustAnchorID = resp.TrustAnchor.TrustAnchorId
	} else {
		ko.Status.TrustAnchorID = nil
	}
	if resp.TrustAnchor.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.TrustAnchor.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.TrustAnchorID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetTrustAnchorInput, error) {
	res := &svcsdk.GetTrustAnchorInput{}

	if r.ko.Status.TrustAnchorID != nil {
		res.TrustAnchorId = r.ko.Status.TrustAnchorID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateTrustAnchorOutput
	_ = resp
	resp, err = rm.sdkapi.CreateTrustAnchor(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTrustAnchor", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.TrustAnchor.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.TrustAnchor.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.TrustAnchor.Enabled != nil {
		ko.Spec.Enabled = resp.TrustAnchor.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.TrustAnchor.Name != nil {
		ko.Spec.Name = resp.TrustAnchor.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.TrustAnchor.NotificationSettings != nil {
		f3 := []*svcapitypes.NotificationSetting{}
		for _, f3iter := range resp.TrustAnchor.NotificationSettings {
			f3elem := &svcapitypes.NotificationSetting{}
			if f3iter.Channel != "" {
				f3elem.Channel = aws.String(string(f3iter.Channel))
			}
			if f3iter.Enabled != nil {
				f3elem.Enabled = f3iter.Enabled
			}
			if f3iter.Event != "" {
				f3elem.Event = aws.String(string(f3iter.Event))
			}
			if f3iter.Threshold != nil {
				thresholdCopy := int64(*f3iter.Threshold)
				f3elem.Threshold = &thresholdCopy
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.NotificationSettings = f3
	} else {
		ko.Spec.NotificationSettings = nil
	}
	if resp.TrustAnchor.Source != nil {
		f4 := &svcapitypes.Source{}
		if resp.TrustAnchor.Source.SourceData != nil {
			f4f0 := &svcapitypes.SourceData{}
			switch resp.TrustAnchor.Source.SourceData.(type) {
			case *svcsdktypes.SourceDataMemberAcmPcaArn:
				f4f0f0 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberAcmPcaArn)
				if f4f0f0 != nil {
					f4f0.ACMPCAARN = &f4f0f0.Value
				}
			case *svcsdktypes.SourceDataMemberX509CertificateData:
				f4f0f1 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberX509CertificateData)
				if f4f0f1 != nil {
					f4f0.X509CertificateData = &f4f0f1.Value
				}
			}
			f4.SourceData = f4f0
		}
		if resp.TrustAnchor.Source.SourceType != "" {
			f4.SourceType = aws.String(string(resp.TrustAnchor.Source.SourceType))
		}
		ko.Spec.Source = f4
	} else {
		ko.Spec.Source = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TrustAnchor.TrustAnchorArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TrustAnchor.TrustAnchorArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.TrustAnchor.TrustAnchorId != nil {
		ko.Status.TrustAnchorID = resp.TrustAnchor.TrustAnchorId
	} else {
		ko.Status.TrustAnchorID = nil
	}
	if resp.TrustAnchor.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.TrustAnchor.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTrustAnchorInput, error) {
	res := &svcsdk.CreateTrustAnchorInput{}

	if r.ko.Spec.Enabled != nil {
		res.Enabled = r.ko.Spec.Enabled
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NotificationSettings != nil {
		f2 := []svcsdktypes.NotificationSetting{}
		for _, f2iter := range r.ko.Spec.NotificationSettings {
			f2elem := &svcsdktypes.NotificationSetting{}
			if f2iter.Channel != nil {
				f2elem.Channel = svcsdktypes.NotificationChannel(*f2iter.Channel)
			}
			if f2iter.Enabled != nil {
				f2elem.Enabled = f2iter.Enabled
			}
			if f2iter.Event != nil {
				f2elem.Event = svcsdktypes.NotificationEvent(*f2iter.Event)
			}
			if f2iter.Threshold != nil {
				thresholdCopy0 := *f2iter.Threshold
				if thresholdCopy0 > math.MaxInt32 || thresholdCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field threshold is of type int32")
				}
				thresholdCopy := int32(thresholdCopy0)
				f2elem.Threshold = &thresholdCopy
			}
			f2 = append(f2, *f2elem)
		}
		res.NotificationSettings = f2
	}
	if r.ko.Spec.Source != nil {
		f3 := &svcsdktypes.Source{}
		if r.ko.Spec.Source.SourceData != nil {
			var f3f0 svcsdktypes.SourceData
			isInterfaceSet := false
			if r.ko.Spec.Source.SourceData.ACMPCAARN != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AcmPcaArn"))
				}
				f3f0f0Parent := &svcsdktypes.SourceDataMemberAcmPcaArn{}
				f3f0f0Parent.Value = *r.ko.Spec.Source.SourceData.ACMPCAARN
				f3f0 = f3f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.Source.SourceData.X509CertificateData != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for X509CertificateData"))
				}
				f3f0f1Parent := &svcsdktypes.SourceDataMemberX509CertificateData{}
				f3f0f1Parent.Value = *r.ko.Spec.Source.SourceData.X509CertificateData
				f3f0 = f3f0f1Parent
				isInterfaceSet = true
			}
			f3.SourceData = f3f0
		}
		if r.ko.Spec.Source.SourceType != nil {
			f3.SourceType = svcsdktypes.TrustAnchorType(*r.ko.Spec.Source.SourceType)
		}
		res.Source = f3
	}
	if r.ko.Spec.Tags != nil {
		f4 := []svcsdktypes.Tag{}
		for _, f4iter := range r.ko.Spec.Tags {
			f4elem := &svcsdktypes.Tag{}
			if f4iter.Key != nil {
				f4elem.Key = f4iter.Key
			}
			if f4iter.Value != nil {
				f4elem.Value = f4iter.Value
			}
			f4 = append(f4, *f4elem)
		}
		res.Tags = f4
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// Sync enabled/disabled state after update (Enable/Disable are separate API calls)
	if desired.ko.Spec.Enabled != nil {
		desiredEnabled := *desired.ko.Spec.Enabled
		currentEnabled := true
		if latest.ko.Spec.Enabled != nil {
			currentEnabled = *latest.ko.Spec.Enabled
		}
		if desiredEnabled != currentEnabled {
			if desiredEnabled {
				_, err = rm.sdkapi.EnableTrustAnchor(ctx, &svcsdk.EnableTrustAnchorInput{
					TrustAnchorId: latest.ko.Status.TrustAnchorID,
				})
			} else {
				_, err = rm.sdkapi.DisableTrustAnchor(ctx, &svcsdk.DisableTrustAnchorInput{
					TrustAnchorId: latest.ko.Status.TrustAnchorID,
				})
			}
			if err != nil {
				return nil, err
			}
		}
	}

	var resp *svcsdk.UpdateTrustAnchorOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateTrustAnchor(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateTrustAnchor", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.TrustAnchor.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.TrustAnchor.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.TrustAnchor.Enabled != nil {
		ko.Spec.Enabled = resp.TrustAnchor.Enabled
	} else {
		ko.Spec.Enabled = nil
	}
	if resp.TrustAnchor.Name != nil {
		ko.Spec.Name = resp.TrustAnchor.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.TrustAnchor.NotificationSettings != nil {
		f3 := []*svcapitypes.NotificationSetting{}
		for _, f3iter := range resp.TrustAnchor.NotificationSettings {
			f3elem := &svcapitypes.NotificationSetting{}
			if f3iter.Channel != "" {
				f3elem.Channel = aws.String(string(f3iter.Channel))
			}
			if f3iter.Enabled != nil {
				f3elem.Enabled = f3iter.Enabled
			}
			if f3iter.Event != "" {
				f3elem.Event = aws.String(string(f3iter.Event))
			}
			if f3iter.Threshold != nil {
				thresholdCopy := int64(*f3iter.Threshold)
				f3elem.Threshold = &thresholdCopy
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.NotificationSettings = f3
	} else {
		ko.Spec.NotificationSettings = nil
	}
	if resp.TrustAnchor.Source != nil {
		f4 := &svcapitypes.Source{}
		if resp.TrustAnchor.Source.SourceData != nil {
			f4f0 := &svcapitypes.SourceData{}
			switch resp.TrustAnchor.Source.SourceData.(type) {
			case *svcsdktypes.SourceDataMemberAcmPcaArn:
				f4f0f0 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberAcmPcaArn)
				if f4f0f0 != nil {
					f4f0.ACMPCAARN = &f4f0f0.Value
				}
			case *svcsdktypes.SourceDataMemberX509CertificateData:
				f4f0f1 := resp.TrustAnchor.Source.SourceData.(*svcsdktypes.SourceDataMemberX509CertificateData)
				if f4f0f1 != nil {
					f4f0.X509CertificateData = &f4f0f1.Value
				}
			}
			f4.SourceData = f4f0
		}
		if resp.TrustAnchor.Source.SourceType != "" {
			f4.SourceType = aws.String(string(resp.TrustAnchor.Source.SourceType))
		}
		ko.Spec.Source = f4
	} else {
		ko.Spec.Source = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TrustAnchor.TrustAnchorArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TrustAnchor.TrustAnchorArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.TrustAnchor.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.TrustAnchor.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateTrustAnchorInput, error) {
	res := &svcsdk.UpdateTrustAnchorInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Source != nil {
		f1 := &svcsdktypes.Source{}
		if r.ko.Spec.Source.SourceData != nil {
			var f1f0 svcsdktypes.SourceData
			isInterfaceSet := false
			if r.ko.Spec.Source.SourceData.ACMPCAARN != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AcmPcaArn"))
				}
				f1f0f0Parent := &svcsdktypes.SourceDataMemberAcmPcaArn{}
				f1f0f0Parent.Value = *r.ko.Spec.Source.SourceData.ACMPCAARN
				f1f0 = f1f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.Source.SourceData.X509CertificateData != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for X509CertificateData"))
				}
				f1f0f1Parent := &svcsdktypes.SourceDataMemberX509CertificateData{}
				f1f0f1Parent.Value = *r.ko.Spec.Source.SourceData.X509CertificateData
				f1f0 = f1f0f1Parent
				isInterfaceSet = true
			}
			f1.SourceData = f1f0
		}
		if r.ko.Spec.Source.SourceType != nil {
			f1.SourceType = svcsdktypes.TrustAnchorType(*r.ko.Spec.Source.SourceType)
		}
		res.Source = f1
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	// Disable trust anchor before deletion (API requirement)
	if r.ko.Spec.Enabled == nil || *r.ko.Spec.Enabled {
		_, _ = rm.sdkapi.DisableTrustAnchor(ctx, &svcsdk.DisableTrustAnchorInput{
			TrustAnchorId: r.ko.Status.TrustAnchorID,
		})
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteTrustAnchorOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteTrustAnchor(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTrustAnchor", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTrustAnchorInput, error) {
	res := &svcsdk.DeleteTrustAnchorInput{}

	if r.ko.Status.TrustAnchorID != nil {
		res.TrustAnchorId = r.ko.Status.TrustAnchorID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.TrustAnchor,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ResourceNotFoundException",
		"ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
