// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type CertificateField string

const (
	CertificateField_x509Subject CertificateField = "x509Subject"
	CertificateField_x509Issuer  CertificateField = "x509Issuer"
	CertificateField_x509SAN     CertificateField = "x509SAN"
)

type NotificationChannel string

const (
	NotificationChannel_ALL NotificationChannel = "ALL"
)

type NotificationEvent string

const (
	NotificationEvent_CA_CERTIFICATE_EXPIRY         NotificationEvent = "CA_CERTIFICATE_EXPIRY"
	NotificationEvent_END_ENTITY_CERTIFICATE_EXPIRY NotificationEvent = "END_ENTITY_CERTIFICATE_EXPIRY"
)

type TrustAnchorType string

const (
	TrustAnchorType_AWS_ACM_PCA            TrustAnchorType = "AWS_ACM_PCA"
	TrustAnchorType_CERTIFICATE_BUNDLE     TrustAnchorType = "CERTIFICATE_BUNDLE"
	TrustAnchorType_SELF_SIGNED_REPOSITORY TrustAnchorType = "SELF_SIGNED_REPOSITORY"
)
