// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ProfileSpec defines the desired state of Profile.
type ProfileSpec struct {

	// Used to determine if a custom role session name will be accepted in a temporary
	// credential request.
	AcceptRoleSessionName *bool `json:"acceptRoleSessionName,omitempty"`
	// Used to determine how long sessions vended using this profile are valid for.
	// See the Expiration section of the CreateSession API documentation (https://docs.aws.amazon.com/rolesanywhere/latest/userguide/authentication-create-session.html#credentials-object)page
	// for more details. In requests, if this value is not provided, the default
	// value will be 3600.
	DurationSeconds *int64 `json:"durationSeconds,omitempty"`
	// Specifies whether the profile is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// A list of managed policy ARNs that apply to the vended session credentials.
	ManagedPolicyARNs []*string `json:"managedPolicyARNs,omitempty"`
	// The name of the profile.
	//
	// Regex Pattern: `^[ a-zA-Z0-9-_]*$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Specifies whether instance properties are required in temporary credential
	// requests with this profile.
	RequireInstanceProperties *bool `json:"requireInstanceProperties,omitempty"`
	// A list of IAM roles that this profile can assume in a temporary credential
	// request.
	RoleARNs []*string                                  `json:"roleARNs,omitempty"`
	RoleRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"roleRefs,omitempty"`
	// A session policy that applies to the trust boundary of the vended session
	// credentials.
	SessionPolicy *string `json:"sessionPolicy,omitempty"`
	// The tags to attach to the profile.
	Tags []*Tag `json:"tags,omitempty"`
}

// ProfileStatus defines the observed state of Profile
type ProfileStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// A mapping applied to the authenticating end-entity certificate.
	// +kubebuilder:validation:Optional
	AttributeMappings []*AttributeMapping `json:"attributeMappings,omitempty"`
	// The ISO-8601 timestamp when the profile was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The Amazon Web Services account that created the profile.
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty"`
	// The unique identifier of the profile.
	//
	// Regex Pattern: `[a-f0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}`
	// +kubebuilder:validation:Optional
	ProfileID *string `json:"profileID,omitempty"`
	// The ISO-8601 timestamp when the profile was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Profile is the Schema for the Profiles API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Profile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ProfileSpec   `json:"spec,omitempty"`
	Status            ProfileStatus `json:"status,omitempty"`
}

// ProfileList contains a list of Profile
// +kubebuilder:object:root=true
type ProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Profile `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Profile{}, &ProfileList{})
}
