// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrustAnchorSpec defines the desired state of TrustAnchor.
type TrustAnchorSpec struct {

	// Specifies whether the trust anchor is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The name of the trust anchor.
	//
	// Regex Pattern: `^[ a-zA-Z0-9-_]*$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A list of notification settings to be associated to the trust anchor.
	NotificationSettings []*NotificationSetting `json:"notificationSettings,omitempty"`
	// The trust anchor type and its related certificate data.
	// +kubebuilder:validation:Required
	Source *Source `json:"source"`
	// The tags to attach to the trust anchor.
	Tags []*Tag `json:"tags,omitempty"`
}

// TrustAnchorStatus defines the observed state of TrustAnchor
type TrustAnchorStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ISO-8601 timestamp when the trust anchor was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The unique identifier of the trust anchor.
	//
	// Regex Pattern: `[a-f0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}`
	// +kubebuilder:validation:Optional
	TrustAnchorID *string `json:"trustAnchorID,omitempty"`
	// The ISO-8601 timestamp when the trust anchor was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// TrustAnchor is the Schema for the TrustAnchors API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type TrustAnchor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TrustAnchorSpec   `json:"spec,omitempty"`
	Status            TrustAnchorStatus `json:"status,omitempty"`
}

// TrustAnchorList contains a list of TrustAnchor
// +kubebuilder:object:root=true
type TrustAnchorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustAnchor `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TrustAnchor{}, &TrustAnchorList{})
}
