// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = ackv1alpha1.AWSAccountID("")
)

// A mapping applied to the authenticating end-entity certificate.
type AttributeMapping struct {
	CertificateField *string        `json:"certificateField,omitempty"`
	MappingRules     []*MappingRule `json:"mappingRules,omitempty"`
}

// The state of the certificate revocation list (CRL) after a read or write
// operation.
type CRLDetail struct {
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	CRLARN         *string      `json:"crlARN,omitempty"`
	CRLID          *string      `json:"crlID,omitempty"`
	Enabled        *bool        `json:"enabled,omitempty"`
	Name           *string      `json:"name,omitempty"`
	TrustAnchorARN *string      `json:"trustAnchorARN,omitempty"`
	UpdatedAt      *metav1.Time `json:"updatedAt,omitempty"`
}

// A record of a presented X509 credential from a temporary credential request.
type CredentialSummary struct {
	Enabled             *bool        `json:"enabled,omitempty"`
	Failed              *bool        `json:"failed,omitempty"`
	Issuer              *string      `json:"issuer,omitempty"`
	SeenAt              *metav1.Time `json:"seenAt,omitempty"`
	SerialNumber        *string      `json:"serialNumber,omitempty"`
	X509CertificateData *string      `json:"x509CertificateData,omitempty"`
}

// A key-value pair you set that identifies a property of the authenticating
// instance.
type InstanceProperty struct {
	Failed *bool        `json:"failed,omitempty"`
	SeenAt *metav1.Time `json:"seenAt,omitempty"`
}

// A single mapping entry for each supported specifier or sub-field.
type MappingRule struct {
	Specifier *string `json:"specifier,omitempty"`
}

// Customizable notification settings that will be applied to notification events.
// IAM Roles Anywhere consumes these settings while notifying across multiple
// channels - CloudWatch metrics, EventBridge, and Health Dashboard.
type NotificationSetting struct {
	Channel   *string `json:"channel,omitempty"`
	Enabled   *bool   `json:"enabled,omitempty"`
	Event     *string `json:"event,omitempty"`
	Threshold *int64  `json:"threshold,omitempty"`
}

// The state of a notification setting.
//
// A notification setting includes information such as event name, threshold,
// status of the notification setting, and the channel to notify.
type NotificationSettingDetail struct {
	Channel      *string `json:"channel,omitempty"`
	ConfiguredBy *string `json:"configuredBy,omitempty"`
	Enabled      *bool   `json:"enabled,omitempty"`
	Event        *string `json:"event,omitempty"`
	Threshold    *int64  `json:"threshold,omitempty"`
}

// A notification setting key to reset. A notification setting key includes
// the event and the channel.
type NotificationSettingKey struct {
	Channel *string `json:"channel,omitempty"`
	Event   *string `json:"event,omitempty"`
}

// The state of the profile after a read or write operation.
type ProfileDetail struct {
	AcceptRoleSessionName     *bool               `json:"acceptRoleSessionName,omitempty"`
	AttributeMappings         []*AttributeMapping `json:"attributeMappings,omitempty"`
	CreatedAt                 *metav1.Time        `json:"createdAt,omitempty"`
	CreatedBy                 *string             `json:"createdBy,omitempty"`
	DurationSeconds           *int64              `json:"durationSeconds,omitempty"`
	Enabled                   *bool               `json:"enabled,omitempty"`
	ManagedPolicyARNs         []*string           `json:"managedPolicyARNs,omitempty"`
	Name                      *string             `json:"name,omitempty"`
	ProfileARN                *string             `json:"profileARN,omitempty"`
	ProfileID                 *string             `json:"profileID,omitempty"`
	RequireInstanceProperties *bool               `json:"requireInstanceProperties,omitempty"`
	RoleARNs                  []*string           `json:"roleARNs,omitempty"`
	SessionPolicy             *string             `json:"sessionPolicy,omitempty"`
	UpdatedAt                 *metav1.Time        `json:"updatedAt,omitempty"`
}

// The trust anchor type and its related certificate data.
type Source struct {
	// The data field of the trust anchor depending on its type.
	SourceData *SourceData `json:"sourceData,omitempty"`
	SourceType *string     `json:"sourceType,omitempty"`
}

// The data field of the trust anchor depending on its type.
type SourceData struct {
	ACMPCAARN *string `json:"acmPCAARN,omitempty"`
	// Reference field for ACMPCAARN
	ACMPCARef           *ackv1alpha1.AWSResourceReferenceWrapper `json:"acmPCARef,omitempty"`
	X509CertificateData *string                                  `json:"x509CertificateData,omitempty"`
}

// The state of the subject after a read or write operation.
type SubjectDetail struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Enabled     *bool        `json:"enabled,omitempty"`
	LastSeenAt  *metav1.Time `json:"lastSeenAt,omitempty"`
	SubjectARN  *string      `json:"subjectARN,omitempty"`
	SubjectID   *string      `json:"subjectID,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
	X509Subject *string      `json:"x509Subject,omitempty"`
}

// A summary representation of subjects.
type SubjectSummary struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Enabled     *bool        `json:"enabled,omitempty"`
	LastSeenAt  *metav1.Time `json:"lastSeenAt,omitempty"`
	SubjectARN  *string      `json:"subjectARN,omitempty"`
	SubjectID   *string      `json:"subjectID,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
	X509Subject *string      `json:"x509Subject,omitempty"`
}

// A label that consists of a key and value you define.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// The state of the trust anchor after a read or write operation.
type TrustAnchorDetail struct {
	CreatedAt            *metav1.Time                 `json:"createdAt,omitempty"`
	Enabled              *bool                        `json:"enabled,omitempty"`
	Name                 *string                      `json:"name,omitempty"`
	NotificationSettings []*NotificationSettingDetail `json:"notificationSettings,omitempty"`
	// The trust anchor type and its related certificate data.
	Source         *Source      `json:"source,omitempty"`
	TrustAnchorARN *string      `json:"trustAnchorARN,omitempty"`
	TrustAnchorID  *string      `json:"trustAnchorID,omitempty"`
	UpdatedAt      *metav1.Time `json:"updatedAt,omitempty"`
}
